networks:
  net:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: multitenant-backend
    container_name: multitenant-backend
    environment:
      - BACKEND_DATABASE_URL=${BACKEND_DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 8020:8020
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8020"
    volumes:
      - ./backend:/app
      # - ./logs:/app/logs
    restart: always
    networks:
      - net
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: multitenant-postgres
    hostname: multitenant-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/datastore:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - net
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - net
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"