# Use a slim version of Python 3.12
FROM python:3.12.3-slim

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install poetry
RUN pip install --upgrade pip setuptools wheel poetry

# Set the working directory
WORKDIR /app

# Copy the poetry files for dependency installation
COPY ./pyproject.toml* ./poetry.lock* ./
RUN poetry install --no-interaction --no-ansi --no-root --no-dev

COPY . /app
ENV PYTHONPATH /app

# Expose the port on which the FastAPI app will run
EXPOSE 8020
